#!/bin/bash

rm -rf tutorials/*
for folder in $(ls content/tutorials); do
	echo "Generating $folder"
	TITLE=$(cat content/tutorials/${folder}/TITLE)
	mkdir -p tutorials/${folder}
	cat includes/header.html | sed  "s/{{TITLE}}/$TITLE/" > tutorials/${folder}/index.html
	pandoc content/tutorials/${folder}/text.md >> tutorials/${folder}/index.html
	cat includes/footer.html >> tutorials/${folder}/index.html	
done;